name = "dr-lohith-portfolio-api"
main = "worker/index.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
AUTH_MODE = "SESSION"
GITHUB_CLIENT_ID = "Ov23li8GJg9PlPGefXJZ"
ADMIN_GITHUB_USERS = "175527963,39591861"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "c60f96de-636b-43d8-98c4-c645dd3b53ee"
migrations_dir = "db/migrations"

# [[r2_buckets]]
# binding = "ASSETS_BUCKET"
# bucket_name = "portfolio-assets"

[assets]
directory = "./dist-site"
binding = "ASSETS"
